In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
import warnings

In [2]:
clients=pd.read_csv("clients.csv",encoding="gbk")
clients.head(2)

   client_id sex  birth_date  district_id
0          1   女  1970-12-13           18
1          2   男  1945-02-04            1

In [3]:
clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   client_id    5369 non-null   int64
 1   sex          5369 non-null   object
 2   birth_date   5369 non-null   object
 3   district_id  5369 non-null   int64
dtypes: int64(2), object(2)
memory usage: 167.9+ KB

In [4]:
clients["birth_date"]=pd.to_datetime(clients["birth_date"],errors="coerce")
clients.info()
clients.head(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   client_id    5369 non-null   int64
 1   sex          5369 non-null   object
 2   birth_date   5369 non-null   datetime64[ns]
 3   district_id  5369 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 167.9+ KB

   client_id sex birth_date  district_id
0          1   女 1970-12-13           18

In [5]:
accounts=pd.read_csv("accounts.csv",encoding="gbk")
accounts.head(2)

   account_id  district_id frequency        date
0         576           55        月结  1993-01-01
1        3818           74        月结  1993-01-01

In [6]:
accounts["date"]=pd.to_datetime(accounts["date"],errors="coerce")
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   account_id   4500 non-null   int64
 1   district_id  4500 non-null   int64
 2   frequency    4500 non-null   object
 3   date         4500 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 140.8+ KB

In [7]:
disp=pd.read_csv("disp.csv",encoding="gbk")
disp.head(2)

   disp_id  client_id  account_id type
0        1          1           1  所有者
1        2          2           2  所有者

In [8]:
loans=pd.read_csv("loans.csv",encoding="gbk")
loans.head(2)

   loan_id  account_id        date  amount  duration  payments status
0     5314        1787  1993-07-05   96396        12      8033      B
1     5316        1801  1993-07-11  165960        36      4610      A

In [9]:
loans["date"]=pd.to_datetime(loans["date"],errors="coerce")
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   loan_id     682 non-null    int64
 1   account_id  682 non-null    int64
 2   date        682 non-null    datetime64[ns]
 3   amount      682 non-null    int64
 4   duration    682 non-null    int64
 5   payments    682 non-null    int64
 6   status      682 non-null    object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 37.4+ KB

In [10]:
card=pd.read_csv("card.csv",encoding="gbk")
card.head(2)

   card_id  disp_id      issued type
0     1005     9285  1993-11-07  普通卡
1      104      588  1994-01-19  普通卡

In [11]:
card["issued"]=pd.to_datetime(card["issued"],errors="coerce")

In [12]:
trans=pd.read_csv("trans.csv",encoding="gbk")
trans.head(2)

C:\Users\胡勇\AppData\Local\Temp\ipykernel_33024\208082092.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  trans=pd.read_csv("trans.csv",encoding="gbk")

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,1993-01-01,贷,信贷资金,$700,$700,NaN,NaN,NaN
1,171812,576,1993-01-01,贷,信贷资金,$900,$900,NaN,NaN,NaN

In [13]:
trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056320 entries, 0 to 1056319
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   trans_id    1056320 non-null  int64
 1   account_id  1056320 non-null  int64
 2   date        1056320 non-null  object
 3   type        1056320 non-null  object
 4   operation   873206 non-null   object
 5   amount      1056320 non-null  object
 6   balance     1056320 non-null  object
 7   k_symbol    521006 non-null   object
 8   bank        273508 non-null   object
 9   account     295389 non-null   float64
dtypes: float64(1), int64(2), object(7)
memory usage: 80.6+ MB

In [14]:
trans["amount"]=trans["amount"].str.replace("$","").str.replace(",","").astype(float,errors="ignore")
trans["balance"]=trans["balance"].str.replace("$","").str.replace(",","").astype(float,errors="ignore")
trans.head(4)

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,1993-01-01,贷,信贷资金,700.0,700.0,NaN,NaN,NaN
1,171812,576,1993-01-01,贷,信贷资金,900.0,900.0,NaN,NaN,NaN
2,207264,704,1993-01-01,贷,信贷资金,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,1993-01-01,贷,信贷资金,600.0,600.0,NaN,NaN,NaN

In [15]:
trans["date"]=pd.to_datetime(trans["date"],errors="coerce")

In [16]:
order=pd.read_csv("order.csv",encoding="gbk")
order.head(2)

   order_id  account_id bank_to  account_to  amount k_symbol
0     29405           3      CD    24485939   327.0      NaN
1     29413           8      IJ    93210345  6712.0      NaN

In [17]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6471 entries, 0 to 6470
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    6471 non-null   int64
 1   account_id  6471 non-null   int64
 2   bank_to     6471 non-null   object
 3   account_to  6471 non-null   int64
 4   amount      6471 non-null   float64
 5   k_symbol    5092 non-null   object
dtypes: float64(1), int64(3), object(2)
memory usage: 303.5+ KB

In [18]:
district=pd.read_csv("district.csv",encoding="gbk")
district.head(2)

   A1     GDP       A4    A10    A11   A12   A13  A14   A15   a16
0   1  283894  1204953  100.0  12541  0.29  0.43  167  35.6  41.1
1   2   11655    88884   46.7   8507  1.67  1.85  132  12.1  15.0

In [19]:
## 信用卡关联disp，获得账户号account_id

In [20]:
card=pd.merge(card,disp[["disp_id","account_id"]],on="disp_id",how="left")
card.head(4)

   card_id  disp_id     issued type  account_id
0     1005     9285 1993-11-07  普通卡        7753
1      104      588 1994-01-19  普通卡         489
2      747     4915 1994-02-05  普通卡        4078
3       70      439 1994-02-08  普通卡         361

In [21]:
client_account = pd.merge(clients, disp, on='client_id', how='left')
client_account = pd.merge(client_account, accounts, on='account_id', how='left', suffixes=('', '_account'))
client_account = pd.merge(client_account, district, left_on='district_id', right_on='A1', how='left', suffixes=('', '_district'))

In [22]:
client_account.head(3)

,client_id,sex,birth_date,district_id,disp_id,account_id,type,district_id_account,frequency,date,A1,GDP,A4,A10,A11,A12,A13,A14,A15,a16
0,1,女,1970-12-13,18,1,1,所有者,18,月结,1995-03-24,18,12527,70699,65.3,8968,2.83,3.35,131,12.3,13.5
1,2,男,1945-02-04,1,2,2,所有者,1,月结,1993-02-26,1,283894,1204953,100.0,12541,0.29,0.43,167,35.6,41.1
2,3,女,1940-10-09,1,3,2,用户,1,月结,1993-02-26,1,283894,1204953,100.0,12541,0.29,0.43,167,35.6,41.1

In [23]:
current_date=datetime.now()
current_date

datetime.datetime(2026, 7, 13, 22, 6, 46, 831183)

In [24]:
client_account['age'] = (current_date - client_account['birth_date']).dt.days // 365
client_account.head(4)

,client_id,sex,birth_date,district_id,disp_id,account_id,type,district_id_account,frequency,date,...,GDP,A4,A10,A11,A12,A13,A14,A15,a16,age
0,1,女,1970-12-13,18,1,1,所有者,18,月结,1995-03-24,...,12527,70699,65.3,8968,2.83,3.35,131,12.3,13.5,55
1,2,男,1945-02-04,1,2,2,所有者,1,月结,1993-02-26,...,283894,1204953,100.0,12541,0.29,0.43,167,35.6,41.1,81
2,3,女,1940-10-09,1,3,2,用户,1,月结,1993-02-26,...,283894,1204953,100.0,12541,0.29,0.43,167,35.6,41.1,85
3,4,男,1956-12-01,5,4,3,所有者,5,月结,1997-07-07,...,13452,95616,51.4,9307,3.85,4.43,118,13.7,15.9,69

In [25]:
client_account=client_account.drop(columns="age")
client_account.head()

,client_id,sex,birth_date,district_id,disp_id,account_id,type,district_id_account,frequency,date,A1,GDP,A4,A10,A11,A12,A13,A14,A15,a16
0,1,女,1970-12-13,18,1,1,所有者,18,月结,1995-03-24,18,12527,70699,65.3,8968,2.83,3.35,131,12.3,13.5
1,2,男,1945-02-04,1,2,2,所有者,1,月结,1993-02-26,1,283894,1204953,100.0,12541,0.29,0.43,167,35.6,41.1
2,3,女,1940-10-09,1,3,2,用户,1,月结,1993-02-26,1,283894,1204953,100.0,12541,0.29,0.43,167,35.6,41.1
3,4,男,1956-12-01,5,4,3,所有者,5,月结,1997-07-07,5,13452,95616,51.4,9307,3.85,4.43,118,13.7,15.9
4,5,女,1960-07-03,5,5,3,用户,5,月结,1997-07-07,5,13452,95616,51.4,9307,3.85,4.43,118,13.7,15.9

In [26]:
stat_cut_date=max(trans["date"].max(),loans["date"].max())
stat_cut_date

Timestamp('1998-12-31 00:00:00')

In [29]:
client_account['age']=(stat_cut_date-client_account['birth_date']).dt.days//365
client_account['account_open_years'] = (stat_cut_date - client_account['date']).dt.days // 365
client_account.head(4)

,client_id,sex,birth_date,district_id,disp_id,account_id,type,district_id_account,frequency,date,...,A4,A10,A11,A12,A13,A14,A15,a16,age,account_open_years
0,1,女,1970-12-13,18,1,1,所有者,18,月结,1995-03-24,...,70699,65.3,8968,2.83,3.35,131,12.3,13.5,28,3
1,2,男,1945-02-04,1,2,2,所有者,1,月结,1993-02-26,...,1204953,100.0,12541,0.29,0.43,167,35.6,41.1,53,5
2,3,女,1940-10-09,1,3,2,用户,1,月结,1993-02-26,...,1204953,100.0,12541,0.29,0.43,167,35.6,41.1,58,5
3,4,男,1956-12-01,5,4,3,所有者,5,月结,1997-07-07,...,95616,51.4,9307,3.85,4.43,118,13.7,15.9,42,1

In [30]:
loans.head(5)

   loan_id  account_id       date  amount  duration  payments status
0     5314        1787 1993-07-05   96396        12      8033      B
1     5316        1801 1993-07-11  165960        36      4610      A
2     6863        9188 1993-07-28  127080        60      2118      A
3     5325        1843 1993-08-03  105804        36      2939      A
4     7240       11013 1993-09-06  274740        60      4579      A

In [31]:
#构建贷款新指标
loans_agg=loans.groupby("account_id").agg(
    loan_count=("loan_id","count"),
    total_loan_amount=("amount","sum"),
    avg_loan_duration=("duration","mean"),
    avg_payment=("payments","mean"),
    default_status=("status",lambda x:"违约" if any(i=="B" for i in x) else "正常")
).reset_index()
loans_agg.head()

,account_id,loan_count,total_loan_amount,avg_loan_duration,avg_payment,default_status
0,2,1,80952,24.0,3373.0,正常
1,19,1,30276,12.0,2523.0,违约
2,25,1,30276,12.0,2523.0,正常
3,37,1,318480,60.0,5308.0,正常
4,38,1,110736,48.0,2307.0,正常

In [32]:
client_account=pd.merge(client_account,loans_agg,on="account_id",how="left")
client_account.head()

,client_id,sex,birth_date,district_id,disp_id,account_id,type,district_id_account,frequency,date,...,A14,A15,a16,age,account_open_years,loan_count,total_loan_amount,avg_loan_duration,avg_payment,default_status
0,1,女,1970-12-13,18,1,1,所有者,18,月结,1995-03-24,...,131,12.3,13.5,28,3,NaN,NaN,NaN,NaN,NaN
1,2,男,1945-02-04,1,2,2,所有者,1,月结,1993-02-26,...,167,35.6,41.1,53,5,1.0,80952.0,24.0,3373.0,正常
2,3,女,1940-10-09,1,3,2,用户,1,月结,1993-02-26,...,167,35.6,41.1,58,5,1.0,80952.0,24.0,3373.0,正常
3,4,男,1956-12-01,5,4,3,所有者,5,月结,1997-07-07,...,118,13.7,15.9,42,1,NaN,NaN,NaN,NaN,NaN
4,5,女,1960-07-03,5,5,3,用户,5,月结,1997-07-07,...,118,13.7,15.9,38,1,NaN,NaN,NaN,NaN,NaN

In [33]:
card_agg = card.groupby('account_id').agg(
    card_count=('card_id', 'count'),
    max_card_age=('issued', lambda x: (stat_cut_date - x).dt.days.max() // 365),
    card_type_count=('type', 'nunique')
).reset_index()
card_agg.head()

   account_id  card_count  max_card_age  card_type_count
0           7           1             0                1
1          14           1             0                1
2          33           1             3                1
3          34           1             0                1
4          43           1             3                1

In [34]:
client_account = pd.merge(client_account, card_agg, on='account_id', how='left')

In [36]:
trans_agg = trans.groupby('account_id').agg(
    trans_count=('trans_id', 'count'),
    total_trans_amount=('amount', 'sum'),
    avg_trans_amount=('amount', 'mean'),
    balance_avg=('balance', 'mean'),
    credit_trans_count=('type', lambda x: (x == '贷').sum()),
    debit_trans_count=('type', lambda x: (x == '借').sum())
).reset_index()
client_account = pd.merge(client_account, trans_agg, on='account_id', how='left')

In [37]:
client_account.head()

,client_id,sex,birth_date,district_id,disp_id,account_id,type,district_id_account,frequency,date,...,default_status,card_count,max_card_age,card_type_count,trans_count,total_trans_amount,avg_trans_amount,balance_avg,credit_trans_count,debit_trans_count
0,1,女,1970-12-13,18,1,1,所有者,18,月结,1995-03-24,...,NaN,NaN,NaN,NaN,239,375192.0,1569.841004,15994.079498,102,137
1,2,男,1945-02-04,1,2,2,所有者,1,月结,1993-02-26,...,正常,NaN,NaN,NaN,478,3151514.0,6593.125523,36540.780335,173,305
2,3,女,1940-10-09,1,3,2,用户,1,月结,1993-02-26,...,正常,NaN,NaN,NaN,478,3151514.0,6593.125523,36540.780335,173,305
3,4,男,1956-12-01,5,4,3,所有者,5,月结,1997-07-07,...,NaN,NaN,NaN,NaN,117,295030.0,2521.623932,26973.529915,46,71
4,5,女,1960-07-03,5,5,3,用户,5,月结,1997-07-07,...,NaN,NaN,NaN,NaN,117,295030.0,2521.623932,26973.529915,46,71

In [38]:
order_agg = order.groupby('account_id').agg(
    order_count=('order_id', 'count'),
    total_order_amount=('amount', 'sum'),
    avg_order_amount=('amount', 'mean')
).reset_index()
client_account = pd.merge(client_account, order_agg, on='account_id', how='left')

In [39]:
client_account[['loan_count', 'total_loan_amount', 'avg_loan_duration', 'avg_payment']] = client_account[['loan_count', 'total_loan_amount', 'avg_loan_duration', 'avg_payment']].fillna(0)
client_account['default_status'] = client_account['default_status'].fillna('无贷款')
client_account[['card_count', 'max_card_age', 'card_type_count']] = client_account[['card_count', 'max_card_age', 'card_type_count']].fillna(0)
client_account[['trans_count', 'total_trans_amount', 'avg_trans_amount', 'balance_avg', 'credit_trans_count', 'debit_trans_count']] = client_account[['trans_count', 'total_trans_amount', 'avg_trans_amount', 'balance_avg', 'credit_trans_count', 'debit_trans_count']].fillna(0)
client_account[['order_count', 'total_order_amount', 'avg_order_amount']] = client_account[['order_count', 'total_order_amount', 'avg_order_amount']].fillna(0)

In [40]:
client_account.head()

,client_id,sex,birth_date,district_id,disp_id,account_id,type,district_id_account,frequency,date,...,card_type_count,trans_count,total_trans_amount,avg_trans_amount,balance_avg,credit_trans_count,debit_trans_count,order_count,total_order_amount,avg_order_amount
0,1,女,1970-12-13,18,1,1,所有者,18,月结,1995-03-24,...,0.0,239,375192.0,1569.841004,15994.079498,102,137,1.0,2452.0,2452.00
1,2,男,1945-02-04,1,2,2,所有者,1,月结,1993-02-26,...,0.0,478,3151514.0,6593.125523,36540.780335,173,305,2.0,10638.7,5319.35
2,3,女,1940-10-09,1,3,2,用户,1,月结,1993-02-26,...,0.0,478,3151514.0,6593.125523,36540.780335,173,305,2.0,10638.7,5319.35
3,4,男,1956-12-01,5,4,3,所有者,5,月结,1997-07-07,...,0.0,117,295030.0,2521.623932,26973.529915,46,71,3.0,5001.0,1667.00
4,5,女,1960-07-03,5,5,3,用户,5,月结,1997-07-07,...,0.0,117,295030.0,2521.623932,26973.529915,46,71,3.0,5001.0,1667.00

In [41]:
client_account.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   client_id            5369 non-null   int64
 1   sex                  5369 non-null   object
 2   birth_date           5369 non-null   datetime64[ns]
 3   district_id          5369 non-null   int64
 4   disp_id              5369 non-null   int64
 5   account_id           5369 non-null   int64
 6   type                 5369 non-null   object
 7   district_id_account  5369 non-null   int64
 8   frequency            5369 non-null   object
 9   date                 5369 non-null   datetime64[ns]
 10  A1                   5369 non-null   int64
 11  GDP                  5369 non-null   int64
 12  A4                   5369 non-null   int64
 13  A10                  5369 non-null   float64
 14  A11                  5369 non-null   int64
 15  A12                  5308 non-null   float64
 16  A13                  5369 non-null   float64
 17  A14                  5369 non-null   int64
 18  A15                  5308 non-null   float64
 19  a16                  5369 non-null   float64
 20  age                  5369 non-null   int64
 21  account_open_years   5369 non-null   int64
 22  loan_count           5369 non-null   float64
 23  total_loan_amount    5369 non-null   float64
 24  avg_loan_duration    5369 non-null   float64
 25  avg_payment          5369 non-null   float64
 26  default_status       5369 non-null   object
 27  card_count           5369 non-null   float64
 28  max_card_age         5369 non-null   float64
 29  card_type_count      5369 non-null   float64
 30  trans_count          5369 non-null   int64
 31  total_trans_amount   5369 non-null   float64
 32  avg_trans_amount     5369 non-null   float64
 33  balance_avg          5369 non-null   float64
 34  credit_trans_count   5369 non-null   int64
 35  debit_trans_count    5369 non-null   int64
 36  order_count          5369 non-null   float64
 37  total_order_amount   5369 non-null   float64
 38  avg_order_amount     5369 non-null   float64
dtypes: datetime64[ns](2), float64(18), int64(15), object(4)
memory usage: 1.6+ MB

In [42]:
client_account.to_csv("客户基础宽表.csv",index=False)